apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    meta.helm.sh/release-name: kubevela
    meta.helm.sh/release-namespace: vela-system
  creationTimestamp: "2025-02-26T15:01:29Z"
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  name: kubevela-vela-core-admission
  resourceVersion: "984"
  uid: 2bed9c1b-efd2-4a9e-a2ff-db1ebca099f5
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lVTDBSaWw0Q3dwc251d1huT1lkenlWQjJBMEZrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tWMlZpYUc5dmF5QkRRVEFlRncweU5UQTBNVFV3TmpReU1EZGFGdzB6TlRBMApNVE13TmpReU1EZGFNQlV4RXpBUkJnTlZCQU1NQ2xkbFltaHZiMnNnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEdFZCbkxoeHhqd2t4TU1xOGJVTlhQc3NQSXdaK1ZUK0loRzBMbmVlSGkKdzJNTUY1eXg5QytycnduVk5sYWhJYldSWVkrQWJMK00zWjQ4dnNqM09GRjZqUFhUOHFYdWFYa2dXSi9ONUh5dwo0U2pMcE5QK2pOQkhWUXI4b3pEN1Q0SUNXZmRlWVpuSTZTZlhTaHdlRUtCQlBWNnBWSDF4c3ZkQWpHY01WQlAvCmkwemhsbkhLazlzMlpKZTEwZ3p3TXArUlRBRURZbUx2a0UzSHgvNEhoZFlaL2IxUHZIMGRxYUZYVHQyWS9TbFQKUW41SlBCcFhtUkFFVUVzYzBFYUp3UVpGekprajFzT25XeENWR0NJYzc5QjFoaXhMVXB1UERqQVUzWU9jVVQ1SgpZdnpqRjNjVy9lSGF4Q2VsLzhnL3htMEJKSis0OTU4dUJEOFY2ZUlyNUVyN0FnTUJBQUdqVXpCUk1CMEdBMVVkCkRnUVdCQlIwRW9mUHpodXFBaGJBeHN5UGpCb3BmMjY0N2pBZkJnTlZIU01FR0RBV2dCUjBFb2ZQemh1cUFoYkEKeHN5UGpCb3BmMjY0N2pBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCdAovSDI0cUR4N3c1eXZHY05VelpGOUFkRzVxM25ta2NiZUFtdDZNQS9rREFkL0RPZWEveS9jd3hRWS95TFhtK2ZMCmhkWng0Zm1sdTVJd0QwajF1ZzRpenBRdDAwRFZEMkNNcHNQVTRCbmdEbkhQK2dET0plcG5oZml2bXc5b05RdXoKbUVUOU0remh5dlR1QTZpSHRReSt5RUtJbU9qRGM3eGN3UG1MWllpQnpLcFBXenJ2ZFpzSElaNXk4cE9udnl0cwpTY3BuWUZOL0JBOEZBazNXdEJlNTJLMTluZHB1alZLTGdQRk9jSW1rbUhNWmp2Q2ZscndJcnB3SkpOSjVreGt2Ck9mSFJ0NFpVelJSYzUxY2FuZWxCUnZHN3Y0ME5SbWoxR0xXVkttTmFaR0E5N294SFNtcU1xTnRDaFBoMUpnR1IKckVRN1FNa0pDd08xdHB2NHZIMWIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: "https://10.131.101.142:9445/mutating-core-oam-dev-v1beta1-applications"
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mutating.core.oam.dev.v1beta1.applications
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - core.oam.dev
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lVTDBSaWw0Q3dwc251d1huT1lkenlWQjJBMEZrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tWMlZpYUc5dmF5QkRRVEFlRncweU5UQTBNVFV3TmpReU1EZGFGdzB6TlRBMApNVE13TmpReU1EZGFNQlV4RXpBUkJnTlZCQU1NQ2xkbFltaHZiMnNnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEdFZCbkxoeHhqd2t4TU1xOGJVTlhQc3NQSXdaK1ZUK0loRzBMbmVlSGkKdzJNTUY1eXg5QytycnduVk5sYWhJYldSWVkrQWJMK00zWjQ4dnNqM09GRjZqUFhUOHFYdWFYa2dXSi9ONUh5dwo0U2pMcE5QK2pOQkhWUXI4b3pEN1Q0SUNXZmRlWVpuSTZTZlhTaHdlRUtCQlBWNnBWSDF4c3ZkQWpHY01WQlAvCmkwemhsbkhLazlzMlpKZTEwZ3p3TXArUlRBRURZbUx2a0UzSHgvNEhoZFlaL2IxUHZIMGRxYUZYVHQyWS9TbFQKUW41SlBCcFhtUkFFVUVzYzBFYUp3UVpGekprajFzT25XeENWR0NJYzc5QjFoaXhMVXB1UERqQVUzWU9jVVQ1SgpZdnpqRjNjVy9lSGF4Q2VsLzhnL3htMEJKSis0OTU4dUJEOFY2ZUlyNUVyN0FnTUJBQUdqVXpCUk1CMEdBMVVkCkRnUVdCQlIwRW9mUHpodXFBaGJBeHN5UGpCb3BmMjY0N2pBZkJnTlZIU01FR0RBV2dCUjBFb2ZQemh1cUFoYkEKeHN5UGpCb3BmMjY0N2pBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCdAovSDI0cUR4N3c1eXZHY05VelpGOUFkRzVxM25ta2NiZUFtdDZNQS9rREFkL0RPZWEveS9jd3hRWS95TFhtK2ZMCmhkWng0Zm1sdTVJd0QwajF1ZzRpenBRdDAwRFZEMkNNcHNQVTRCbmdEbkhQK2dET0plcG5oZml2bXc5b05RdXoKbUVUOU0remh5dlR1QTZpSHRReSt5RUtJbU9qRGM3eGN3UG1MWllpQnpLcFBXenJ2ZFpzSElaNXk4cE9udnl0cwpTY3BuWUZOL0JBOEZBazNXdEJlNTJLMTluZHB1alZLTGdQRk9jSW1rbUhNWmp2Q2ZscndJcnB3SkpOSjVreGt2Ck9mSFJ0NFpVelJSYzUxY2FuZWxCUnZHN3Y0ME5SbWoxR0xXVkttTmFaR0E5N294SFNtcU1xTnRDaFBoMUpnR1IKckVRN1FNa0pDd08xdHB2NHZIMWIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: "https://10.131.101.142:9445/mutating-core-oam-dev-v1beta1-componentdefinitions"
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mutating.core.oam-dev.v1beta1.componentdefinitions
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - core.oam.dev
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - componentdefinitions
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
