apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  password: bXlwYXNzd29yZA==

---

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-app
spec:
  components: [ ]
  workflow:
    steps:
      - name: read-secret
        type: read-object
        properties:
          apiVersion: v1
          kind: Secret
          name: mysecret
        outputs:
          - name: mypassword1
            valueFrom: |-
              import "encoding/base64"
              base64.Decode(output.value.data["password"])