apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: website
spec:
  components:
    - name: frontend
      type: webservice
      properties:
        image: oamdev/testapp:v1
        cmd: ["node", "server.js"]
        ports:
          - port: 8080
            expose: true
        cpu: "2m"
        memory: "500Mi"
        limit:
          cpu: "5m"
          memory: "1000Mi"
        env:
          - name: FOO
            value: bar
  policies:
    - name: deploy-fluxcd
      type: topology
      properties:
        clusterLabelSelector: { }


