apiVersion: v1
data:
  alternate_base_domains: ""
  atmos_version: master
  aws_account_id: "776719623202"
  aws_region: us-west-2
  base_environment_url: scratch-oamcatct.scratch-needle.guidewire.net
  cluster_name: atmos-scratch-oamcatct
  db_subnet_group_name: atmos-scratch-oamcatct-rds-nonk8s-subnet-group
  default_gwcp_created_by: pod-danville
  default_gwcp_dept_code: "275"
  default_gwcp_maintained_by: pod-danville
  default_gwcp_tenant_name: quadrant-shared
  non_k8s_private_subnet_availability_zone_ids: usw2-az1,usw2-az2,usw2-az3
  non_k8s_private_subnet_groups: subnet-0cce63da934850a2c,subnet-00bc68ea7ef5d06b4,subnet-0045b585bac470c81
  non_k8s_security_group_id: sg-096c0b1d7e4631f06
  private_subnet_groups: subnet-05273414c56fcf38e,subnet-09860986be6825e43,subnet-0f83630218feb3809
  public_subnet_groups: subnet-08ea1b92df869caf2,subnet-081b7be34deba2ca3,subnet-048dcd3cd38aa2e0f
  vpc_id: vpc-0237112867475a088
  vpc_private_route_table_ids: rtb-0c4df795f689a0d18,rtb-05c107ef9acd510c2,rtb-0430b17aba8e534a4
  vpc_private_subnet_cidrs: 10.0.4.0/22,10.0.8.0/22,10.0.12.0/22
  worker_security_group_id: sg-067f9a2693eb94ce1
kind: ConfigMap
metadata:
  name: atmos-cluster-info
