apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: dynamic-configmap-example
  namespace: default
spec:
    components:
      - name: express-cm
        type: configmap-component
        properties:
          secondkey:
            value2:
              value3:
                value4: "1"
    workflow:
        steps:
            - name: read-network-properties
              type: read-object
              outputs:
                - valueFrom: output.value.data["firstkey"]
                  name: output1
                - valueFrom: output.value.data["secondkey"]
                  name: output2
                - valueFrom: output.value.data["thirdkey"]
                  name: output3
                - valueFrom: output.value.data["forthkey"]
                  name: output4
              properties:
                apiVersion: v1
                kind: ConfigMap
                name: atmos-cluster-info
                namespace: default
            - name: apply
              type: apply-component
              properties:
                component: express-cm
              dependsOn:
                - read-network-properties
              inputs:
                - parameterKey: firstkey
                  from: output1
                - parameterKey: secondkey.value1
                  from: output2
                - parameterKey: thirdkey
                  from: output3