apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
    name: kubevelaefshappypathonlycheckingsta-wdrg
    namespace: default
spec:
    components:
      - name: express-server
        type: configmap-component
        properties:
          thirdkey: "3"
          sixthkey: "6"

