apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    meta.helm.sh/release-name: kubevela
    meta.helm.sh/release-namespace: vela-system
  creationTimestamp: "2025-02-26T15:01:29Z"
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  name: kubevela-vela-core-admission
  resourceVersion: "983"
  uid: fcfc8323-112d-47d4-b0af-93f4aaf2c664
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lVVTVtOWRaTU52VWhwVkoxbkhiQ2Q5L2dvUkFnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tWMlZpYUc5dmF5QkRRVEFlRncweU5UQTBNalV3TkRRNE5URmFGdzB6TlRBMApNak13TkRRNE5URmFNQlV4RXpBUkJnTlZCQU1NQ2xkbFltaHZiMnNnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDd2gxSXhPL3lOTEVFUjZoYXlsSHMza01RZ3lHSVRCcXlidVhIMDM0Y1oKZFAzZWxpaTJPWXhhWFhWeUo3aVROZDhaRTRUTFN6aUE0NEZ0OTdCN0Y4T0t6N1FjZGVFNUUybUhwU0crTWp2UwpIMDJMYXp0R0F3ZEJkUVR0cWlZcUNnUkZpTTVzcVBIMDRPejFSUWpRVnlIVmlmY1ZlSUVvenhYbElBMFFLYUJPCk5vcTJUSk9ESk8yTjYrZEEvNExiM0lOOUN3c3RBTlpwVWdlMnhTeCt4YithYnB5U2dXSURuR044QUt1RVZvd1YKVjhMUGIzZUxLUUFyL0NqTVk3VnQyWFlUVHNtUTQ0dEJEYlJkaExpMWhYMUYydzYyUUhKbk5sdGhrN1FxY3pQSgpBWFc3aTgyTnR3eExta3hEMEgwVUpRVXY3UmM1cGpGTWxiTU13M3Z3VWs0QkFnTUJBQUdqVXpCUk1CMEdBMVVkCkRnUVdCQlMyckxpUVVQeXE1Q3pwQy9yUnMzWnVsL3FoZURBZkJnTlZIU01FR0RBV2dCUzJyTGlRVVB5cTVDenAKQy9yUnMzWnVsL3FoZURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBLwpjNHFkZUxlUXlTTm12NjQ5MFl1Q0ozRlZjbXZ6bjcveVd2UDdSK3d0YmIwMDMxZVJscXBkeXNoY1pxL2sydjlRCmhnd0xqTEFXTUFjeitRcHB3UEhkeFp0N1c5Mmo4R3V6MVBEaWR3Lzg3U0VpSjE5OXlHSVJsV1ltK2J5QmsrL3cKV2FiR3JtemtrSU93UEhoVXRxcGRtRE9mcEFVZ3UwZ2hvZ2hkMjBWb0M5czhEQ3hSQVJ0U01tRkxqTFdsSVNLSApoeFU3TnNZWTNoS1pnejdydjV2TmFXbmxaSjY0UEd4QjErL3gxSXBVYjdEK0JNS3NyYnVIOVBYMk5CWnlweHR2CithUmtJcjk5alhoL0VhNHJrYyt0SU4vcWZmNUk3bE9kY255NTZqU2NQM1B4Y2ZKQ1N0MmdLYlo3cVRzbm1QYWEKb2tObWo2V09lb1J2a0ppOFVUcU4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

    url: "https://192.168.0.101:9445/validating-core-oam-dev-v1beta1-traitdefinitions"
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validating.core.oam.dev.v1beta1.traitdefinitions
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - core.oam.dev
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - traitdefinitions
    scope: '*'
  sideEffects: None
  timeoutSeconds: 5
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lVVTVtOWRaTU52VWhwVkoxbkhiQ2Q5L2dvUkFnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tWMlZpYUc5dmF5QkRRVEFlRncweU5UQTBNalV3TkRRNE5URmFGdzB6TlRBMApNak13TkRRNE5URmFNQlV4RXpBUkJnTlZCQU1NQ2xkbFltaHZiMnNnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDd2gxSXhPL3lOTEVFUjZoYXlsSHMza01RZ3lHSVRCcXlidVhIMDM0Y1oKZFAzZWxpaTJPWXhhWFhWeUo3aVROZDhaRTRUTFN6aUE0NEZ0OTdCN0Y4T0t6N1FjZGVFNUUybUhwU0crTWp2UwpIMDJMYXp0R0F3ZEJkUVR0cWlZcUNnUkZpTTVzcVBIMDRPejFSUWpRVnlIVmlmY1ZlSUVvenhYbElBMFFLYUJPCk5vcTJUSk9ESk8yTjYrZEEvNExiM0lOOUN3c3RBTlpwVWdlMnhTeCt4YithYnB5U2dXSURuR044QUt1RVZvd1YKVjhMUGIzZUxLUUFyL0NqTVk3VnQyWFlUVHNtUTQ0dEJEYlJkaExpMWhYMUYydzYyUUhKbk5sdGhrN1FxY3pQSgpBWFc3aTgyTnR3eExta3hEMEgwVUpRVXY3UmM1cGpGTWxiTU13M3Z3VWs0QkFnTUJBQUdqVXpCUk1CMEdBMVVkCkRnUVdCQlMyckxpUVVQeXE1Q3pwQy9yUnMzWnVsL3FoZURBZkJnTlZIU01FR0RBV2dCUzJyTGlRVVB5cTVDenAKQy9yUnMzWnVsL3FoZURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBLwpjNHFkZUxlUXlTTm12NjQ5MFl1Q0ozRlZjbXZ6bjcveVd2UDdSK3d0YmIwMDMxZVJscXBkeXNoY1pxL2sydjlRCmhnd0xqTEFXTUFjeitRcHB3UEhkeFp0N1c5Mmo4R3V6MVBEaWR3Lzg3U0VpSjE5OXlHSVJsV1ltK2J5QmsrL3cKV2FiR3JtemtrSU93UEhoVXRxcGRtRE9mcEFVZ3UwZ2hvZ2hkMjBWb0M5czhEQ3hSQVJ0U01tRkxqTFdsSVNLSApoeFU3TnNZWTNoS1pnejdydjV2TmFXbmxaSjY0UEd4QjErL3gxSXBVYjdEK0JNS3NyYnVIOVBYMk5CWnlweHR2CithUmtJcjk5alhoL0VhNHJrYyt0SU4vcWZmNUk3bE9kY255NTZqU2NQM1B4Y2ZKQ1N0MmdLYlo3cVRzbm1QYWEKb2tObWo2V09lb1J2a0ppOFVUcU4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

    url: "https://192.168.0.101:9445/validating-core-oam-dev-v1beta1-applications"
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validating.core.oam.dev.v1beta1.applications
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - core.oam.dev
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lVVTVtOWRaTU52VWhwVkoxbkhiQ2Q5L2dvUkFnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tWMlZpYUc5dmF5QkRRVEFlRncweU5UQTBNalV3TkRRNE5URmFGdzB6TlRBMApNak13TkRRNE5URmFNQlV4RXpBUkJnTlZCQU1NQ2xkbFltaHZiMnNnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDd2gxSXhPL3lOTEVFUjZoYXlsSHMza01RZ3lHSVRCcXlidVhIMDM0Y1oKZFAzZWxpaTJPWXhhWFhWeUo3aVROZDhaRTRUTFN6aUE0NEZ0OTdCN0Y4T0t6N1FjZGVFNUUybUhwU0crTWp2UwpIMDJMYXp0R0F3ZEJkUVR0cWlZcUNnUkZpTTVzcVBIMDRPejFSUWpRVnlIVmlmY1ZlSUVvenhYbElBMFFLYUJPCk5vcTJUSk9ESk8yTjYrZEEvNExiM0lOOUN3c3RBTlpwVWdlMnhTeCt4YithYnB5U2dXSURuR044QUt1RVZvd1YKVjhMUGIzZUxLUUFyL0NqTVk3VnQyWFlUVHNtUTQ0dEJEYlJkaExpMWhYMUYydzYyUUhKbk5sdGhrN1FxY3pQSgpBWFc3aTgyTnR3eExta3hEMEgwVUpRVXY3UmM1cGpGTWxiTU13M3Z3VWs0QkFnTUJBQUdqVXpCUk1CMEdBMVVkCkRnUVdCQlMyckxpUVVQeXE1Q3pwQy9yUnMzWnVsL3FoZURBZkJnTlZIU01FR0RBV2dCUzJyTGlRVVB5cTVDenAKQy9yUnMzWnVsL3FoZURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBLwpjNHFkZUxlUXlTTm12NjQ5MFl1Q0ozRlZjbXZ6bjcveVd2UDdSK3d0YmIwMDMxZVJscXBkeXNoY1pxL2sydjlRCmhnd0xqTEFXTUFjeitRcHB3UEhkeFp0N1c5Mmo4R3V6MVBEaWR3Lzg3U0VpSjE5OXlHSVJsV1ltK2J5QmsrL3cKV2FiR3JtemtrSU93UEhoVXRxcGRtRE9mcEFVZ3UwZ2hvZ2hkMjBWb0M5czhEQ3hSQVJ0U01tRkxqTFdsSVNLSApoeFU3TnNZWTNoS1pnejdydjV2TmFXbmxaSjY0UEd4QjErL3gxSXBVYjdEK0JNS3NyYnVIOVBYMk5CWnlweHR2CithUmtJcjk5alhoL0VhNHJrYyt0SU4vcWZmNUk3bE9kY255NTZqU2NQM1B4Y2ZKQ1N0MmdLYlo3cVRzbm1QYWEKb2tObWo2V09lb1J2a0ppOFVUcU4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

    url: "https://192.168.0.101:9445/validating-core-oam-dev-v1beta1-componentdefinitions"
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validating.core.oam-dev.v1beta1.componentdefinitions
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - core.oam.dev
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - componentdefinitions
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lVVTVtOWRaTU52VWhwVkoxbkhiQ2Q5L2dvUkFnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tWMlZpYUc5dmF5QkRRVEFlRncweU5UQTBNalV3TkRRNE5URmFGdzB6TlRBMApNak13TkRRNE5URmFNQlV4RXpBUkJnTlZCQU1NQ2xkbFltaHZiMnNnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDd2gxSXhPL3lOTEVFUjZoYXlsSHMza01RZ3lHSVRCcXlidVhIMDM0Y1oKZFAzZWxpaTJPWXhhWFhWeUo3aVROZDhaRTRUTFN6aUE0NEZ0OTdCN0Y4T0t6N1FjZGVFNUUybUhwU0crTWp2UwpIMDJMYXp0R0F3ZEJkUVR0cWlZcUNnUkZpTTVzcVBIMDRPejFSUWpRVnlIVmlmY1ZlSUVvenhYbElBMFFLYUJPCk5vcTJUSk9ESk8yTjYrZEEvNExiM0lOOUN3c3RBTlpwVWdlMnhTeCt4YithYnB5U2dXSURuR044QUt1RVZvd1YKVjhMUGIzZUxLUUFyL0NqTVk3VnQyWFlUVHNtUTQ0dEJEYlJkaExpMWhYMUYydzYyUUhKbk5sdGhrN1FxY3pQSgpBWFc3aTgyTnR3eExta3hEMEgwVUpRVXY3UmM1cGpGTWxiTU13M3Z3VWs0QkFnTUJBQUdqVXpCUk1CMEdBMVVkCkRnUVdCQlMyckxpUVVQeXE1Q3pwQy9yUnMzWnVsL3FoZURBZkJnTlZIU01FR0RBV2dCUzJyTGlRVVB5cTVDenAKQy9yUnMzWnVsL3FoZURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBLwpjNHFkZUxlUXlTTm12NjQ5MFl1Q0ozRlZjbXZ6bjcveVd2UDdSK3d0YmIwMDMxZVJscXBkeXNoY1pxL2sydjlRCmhnd0xqTEFXTUFjeitRcHB3UEhkeFp0N1c5Mmo4R3V6MVBEaWR3Lzg3U0VpSjE5OXlHSVJsV1ltK2J5QmsrL3cKV2FiR3JtemtrSU93UEhoVXRxcGRtRE9mcEFVZ3UwZ2hvZ2hkMjBWb0M5czhEQ3hSQVJ0U01tRkxqTFdsSVNLSApoeFU3TnNZWTNoS1pnejdydjV2TmFXbmxaSjY0UEd4QjErL3gxSXBVYjdEK0JNS3NyYnVIOVBYMk5CWnlweHR2CithUmtJcjk5alhoL0VhNHJrYyt0SU4vcWZmNUk3bE9kY255NTZqU2NQM1B4Y2ZKQ1N0MmdLYlo3cVRzbm1QYWEKb2tObWo2V09lb1J2a0ppOFVUcU4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

    url: "https://192.168.0.101:9445/validating-core-oam-dev-v1beta1-policydefinitions"
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validating.core.oam-dev.v1beta1.policydefinitions
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - core.oam.dev
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - policydefinitions
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
